### ISSUE TITLE
No releases available

### ISSUE THREAD

**Issue by lfourky** [Netcentric/aemmjml#4]
There are currently no releases available, and yet they're referenced here: https://github.com/Netcentric/aemmjml#installation

**Comment by buuhuu** [comment]
Hi @lfourky, you are right, there is no release yet as we have some issues still open. Do you want to use aemmjml in a production setup or for evaluation purpose? In case of the later you can always build and use it as snapshot.

**Comment by buuhuu** [comment]
There is a first release at e40b39dd077f696780f6239f82aa5d0bda6175cb
